In [1]:
import numpy as np

# (10,15,30,45,60) sayılarını numpy dizisi yapınız

In [2]:
np.array([10,15,30,45,60])

array([10, 15, 30, 45, 60])

# (5-15) arasındaki sayılarla numpy dizisi

In [3]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# 50-100 arasında beşer artan numpy dizisi

In [4]:
np.arange(50,100,5)

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

# 10 elemanlı sıfırladan oluşan bir dizi

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 10 elemanlı birlerden oluşan dizi

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# 0-100 arasında eşit aralıklı 5 sayı 

In [7]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

# 10-30 arasında rastgele 5 sayı 

In [9]:
np.random.randint(10,30,5)

array([10, 14, 29, 28, 27])

# [-1,1] aralığında 10 adet sayı

In [15]:
np.random.randn(10)

array([ 0.64796675,  1.16135918, -1.16648066, -0.06885252, -2.70049447,
       -0.87525401,  0.80610669,  0.67981711, -0.74867849, -2.00855722])

# (3x5) boyutlarında (10-50) arasında rastgele bir matris

In [58]:
matris=np.random.randint(10,50,15).reshape(3,5)


In [59]:
print(matris)

[[20 48 28 16 25]
 [33 21 24 47 15]
 [34 35 28 21 33]]


# Üretilen matrisin satır ve sütun sayılarının toplamı

In [76]:
matris.sum(axis=0) #sütun

array([ 87, 104,  80,  84,  73])

In [77]:
matris.sum(axis=1) #satır

array([137, 140, 151])

 # Üretilen matrisin en büyük elemanı

In [64]:
matris.max()

48

 # Üretilen matrisin en küçük elemanı

In [47]:
matris.min()

10

# Üretilen matrisin ortalaması

In [65]:
matris.mean()

28.533333333333335

# Üretilen matrisin en büyük elemanı kaçıncı indekste

In [66]:
matris.argmax()

1

 # (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanı

In [48]:
arr=np.arange(10,20)

In [49]:
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [50]:
arr[:3]

array([10, 11, 12])

# Üretilen diziyi tersten yazdırın

In [51]:
arr[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

# Üretilen matrisin ilk satırını getirin

In [78]:
matris[0]

array([20, 48, 28, 16, 25])

# Üretilen matrisin 2. satır 3. sütündaki elemanı

In [68]:
matris[1,2]

24

# Üretilen matrisin tüm satırlarındaki ilk eleman

In [69]:
matris[:,0]

array([20, 33, 34])

# Üretilen matrisin her bir elemanının karesi

In [71]:
matris**2

array([[ 400, 2304,  784,  256,  625],
       [1089,  441,  576, 2209,  225],
       [1156, 1225,  784,  441, 1089]])

# Üretilen matris elemanlarının hangisi çift elemanlıdır

In [73]:
result=matris%2==0

In [79]:
matris[result]

array([20, 48, 28, 16, 24, 34, 28])

# -50 ile +50 arasında matris (3x5) boyutlarında negatif çift sayılar

In [97]:
matris2=np.random.randint(-50,50,15).reshape(3,5)

In [98]:
matris2

array([[ 21,  27,  41,  21, -18],
       [-28, -34,   4,   2,  37],
       [ 46,  24,  20,   3,   8]])

In [99]:
ciftler=matris2[matris2%2==0]

In [100]:
ciftler

array([-18, -28, -34,   4,   2,  46,  24,  20,   8])

In [102]:
matris2=ciftler[ciftler<0]

In [103]:
matris2

array([-18, -28, -34])